### ISSUE TITLE
ServiceFabricRPHelpers.psm1 [-Provider parameter no longer valid for powershell v5+?]

### ISSUE THREAD

**Issue by tocorobo** [ChackDan/Service-Fabric#15]
The "New-SelfSignedCertificate" in the else block no longer works with powershell v5 (and higher?):

$PspkiVersion = (Get-Module PSPKI).Version
if($PSPKIVersion.Major -ieq 3 -And $PspkiVersion.Minor -ieq 2 -And $PspkiVersion.Build -ieq 5) {
    New-SelfsignedCertificateEx -Subject "CN=$DnsName" -EKU "Server Authentication", "Client authentication" -KeyUsage "KeyEncipherment, DigitalSignature" -Path $NewPfxFilePath -Password $securePassword -Exportable
}
else {
    New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName $DnsName -Provider 'Microsoft Enhanced Cryptographic Provider v1.0' | Export-PfxCertificate -FilePath $NewPfxFilePath -Password $securePassword | Out-Null
}
We got it to work by removing "-Provider 'Microsoft Enhanced Cryptographic Provider v1.0'" from the New-SelfSignedCertificate line.

**Comment by ChackDan** [comment]
Thankyou Tony. Will fix it with the new iteration.
