### ISSUE TITLE
Connection to Service Fabric Cluster Endpoint From Behind Corporate Proxy

### ISSUE THREAD

**Issue by pixelbyaj** [ChackDan/Service-Fabric#23]
How to get connected to SF Cluster Endpoints from behind corporate proxy?
As I am getting below:
WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service... WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM... False WARNING: No connection could be made because the target machine actively refused it 40.117.45.185:19000 Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue. At line:1 char:1 + Connect-ServiceFabricCluster -ConnectionEndpoint mycluster.westus.cloudap ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster

**Comment by ChackDan** [comment]
you need to allow that traffic in ... file a CSS ticket for more guidance https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
