### ISSUE TITLE
A parameter cannot be found that matches parameter name 'Provider'.

### ISSUE THREAD

**Issue by rfcdejong** [ChackDan/Service-Fabric#4]
Line 409 
New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName $DnsName -Provider 'Microsoft Enhanced Cryptographic Provider v1.0' | Export-PfxCertificate -FilePath $NewPfxFilePath -Password $securePassword | Out-Null

results into an error:

Invoke-AddCertToKeyVault : A parameter cannot be found that matches parameter name 'Provider'.

I have been looking around and found only powershell scripts for ProviderName, but not out of the box.

**Comment by ChackDan** [comment]
Make sure that Azure PowerShell 1.0+ is installed on your machine.

**Comment by DavieReid** [comment]
I have the same problem as @rfcdejong  and I am using version 1.5.1 of Azure powershell on a Windows Server 2012 R2 box.

Removing the `-provider` param generates a certificate without issue.

**Comment by vbhadrir** [comment]
@DavieReid, I am having the same problem as you and @rfcdejong. To generate a valid certificate, you mention the workaround of removing the -provider param. How did you remove the -provide param ? can you please provide more details ?

**Comment by DavieReid** [comment]
I edited the ServiceFabricRPHelpers.psm1 file and changed

 ` New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName $DnsName -Provider 'Microsoft Enhanced Cryptographic Provider v1.0' | Export-PfxCertificate -FilePath $NewPfxFilePath -Password $securePassword | Out-Null`

to

` New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName $DnsName | Export-PfxCertificate -FilePath $NewPfxFilePath -Password $securePassword | Out-Null`

I didn't use the certificate created via this method for long.  I had my infrastructure department generate a certificate for me.
