### ISSUE TITLE
Cannot import module from PowerShell

### ISSUE THREAD

**Issue by tommed** [ChackDan/Service-Fabric#7]
When attempting to import this on my Windows 10 laptop, I get the following error:

> Add-Type : Could not load file or assembly
> 'file:///C:\users\tom.medhurst\Desktop\sfmodule\Scripts\ServiceFabricRPHelpers\System.Fabric.CSMTemplate\System.Fabric.CSMTemplate.dll' or
> one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
> At C:\users\tom.medhurst\Desktop\sfmodule\Scripts\ServiceFabricRPHelpers\ServiceFabricRPHelpers.psm1:11 char:1
> - Add-Type -Path "$invocationDir\System.Fabric.CSMTemplate\System.Fabri ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
>   - FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand

I have downloaded the entire contents of the repo and have even tried an escalated powershell but neither seem to work.

The assembly exists, but there must be another dependency etc. that is missing?

Command ran:
`import-module "C:\users\tom.medhurst\Desktop\sfmodule\Scripts\ServiceFabricRPHelpers\ServiceFabricRPHelpers.psm1"`

**Comment by DenisPitcher** [comment]
I ran into the same issue.  Go to the directory of the file in powershell and then run the command as specified in the github documentation.

The Azure documentation suggests importing using the full path, this failed for me with the same error..  The github documentation suggests 
1. Goto module directory
2. Import module  
   Import-Module .\ServiceFabricRPHelpers.psm1

This worked for me

**Comment by tommed** [comment]
Doesn't for me.
https://gist.github.com/anonymous/57404770162b92a730d37e3dabe26935

Ah but this does:
`Import-Module ..\ServiceFabricRPHelpers.psm1`

**Comment by tommed** [comment]
Sorted thanks

**Comment by HakanL** [comment]
I had the same issue, can you update the documentation/readme?
