### ISSUE TITLE
Invoke-AddCertToKeyVault without private key

### ISSUE THREAD

**Issue by Dismissile** [ChackDan/Service-Fabric#8]
The powershell command you created Invoke-AddCertToKeyVault has the following parameters to upload an existing certificate to KeyVault:

-UseExistingCertificate
-ExistingPfxFilePath <string>

The Json blob you create even specifies dataType = 'pfx'

How would I modify this script to upload a certificate that does not contain a private key, e.g. a .cer file instead of a .pfx file?

**Comment by ChackDan** [comment]
SF cluster itself does not care if you used a .cer or .pfx. but I think CRP has an issue with .cer and may not be able to install it. Let me check with them on what they say.

Out of curiosity - why are you trying to use a .cer ? or what is the scenario ?

**Comment by Dismissile** [comment]
My scenario might be invalid but I was trying to install a certificate in the Root Certificate Authorities store. I have some certs that will be signed by that root certificate that currently aren't being trusted. The end goal is to have https for all internal traffic within the cluster. 

What does CRP stand for?

**Comment by ChackDan** [comment]
CRP - Compute Resource Provider. that is the RP that owns the VM  and VMSS resource
